name: Katie Lee Dunbar
markdown: redcarpet
pygments: true
content-root: https://s3-eu-west-1.amazonaws.com/flughafenstrasse
gallerytag:
    dir: images/galleries
    url: /images/galleries
    thumb_width: 150
    thumb_height: 150
    columns: 4